server:
  port: 9280
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinemasdb
    username: cinemas
    password: cinemas123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect